package com.chengukargbo.careeros.questions;
import static org.assertj.core.api.Assertions.*; import org.junit.jupiter.api.Test; import com.chengukargbo.careeros.questions.QuestionEnums.*;
class ApplicationQuestionTest {
 private ApplicationQuestion question(Classification classification){return new ApplicationQuestion(null,null,"why_this_role","Why this role?",AnswerType.TEXT,true,classification,Source.MANUAL);}
 @Test void beginsUnansweredAndManual(){var q=question(Classification.CONTEXTUAL);assertThat(q.getStatus()).isEqualTo(Status.UNANSWERED);assertThat(q.getSource()).isEqualTo(Source.MANUAL);}
 @Test void answerRequiresApplicationSpecificApproval(){var q=question(Classification.CONTEXTUAL);q.answer("Because it fits");assertThat(q.getStatus()).isEqualTo(Status.ANSWERED);assertThat(q.getApprovedAnswer()).isNull();q.approve();assertThat(q.getStatus()).isEqualTo(Status.APPROVED);}
 @Test void suggestionAlwaysNeedsReview(){var q=question(Classification.VERIFIED_REUSABLE);q.suggest(null,"Yes");assertThat(q.getStatus()).isEqualTo(Status.NEEDS_REVIEW);assertThat(q.getApprovedAnswer()).isNull();q.rejectSuggestion();assertThat(q.getStatus()).isEqualTo(Status.UNANSWERED);}
 @Test void blockerIsQuestionOnlyAndCanBeRemoved(){var q=question(Classification.KNOCKOUT);q.block();assertThat(q.getStatus()).isEqualTo(Status.BLOCKED);q.unblock();assertThat(q.getStatus()).isEqualTo(Status.UNANSWERED);}
 @Test void mappingChangePreservesAtsContractAndInvalidatesOldAnswerAuthority(){var q=question(Classification.CONTEXTUAL);q.suggest(null,"Old answer");q.approve();var option=new ApplicationQuestionOption(q,"yes","yes","Yes",0,true);q.reconcileObserved("ats-email","email","Exact ATS wording",AnswerType.TEXT,true,Classification.VERIFIED_REUSABLE,java.util.List.of(option),true);assertThat(q.getExternalQuestionKey()).isEqualTo("ats-email");assertThat(q.getCanonicalQuestionKey()).isEqualTo("email");assertThat(q.getQuestionText()).isEqualTo("Exact ATS wording");assertThat(q.getOptions()).extracting(ApplicationQuestionOption::getLabel).containsExactly("Yes");assertThat(q.getApprovedAnswer()).isNull();assertThat(q.getProposedAnswer()).isNull();assertThat(q.getStatus()).isEqualTo(Status.NEEDS_REVIEW);q.mappingRevoked();assertThat(q.getCanonicalQuestionKey()).isNull();assertThat(q.getStatus()).isEqualTo(Status.NEEDS_REVIEW);}
}
