package com.chengukargbo.careeros.preparation;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import java.util.*;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import org.springframework.test.util.ReflectionTestUtils;
import com.chengukargbo.careeros.applications.*;import com.chengukargbo.careeros.jobs.RemoteType;import com.chengukargbo.careeros.materials.*;import com.chengukargbo.careeros.profile.*;
@ExtendWith(MockitoExtension.class) class ApprovedMaterialPlanServiceTest{
 @Mock ApplicationPreparationSessionRepository sessions;@Mock ApprovedMaterialPlanRepository plans;@Mock ApplicantProfileRepository profiles;@InjectMocks ApprovedMaterialPlanService service;
 @Test void applicationSelectionOutranksProfileDefaultWithoutExposingStorageKey(){ApplicantProfile profile=profile();CareerMaterial selected=material(profile,7L,"Selected");CareerMaterial fallback=material(profile,8L,"Default");profile.setDefaultResumeMaterial(fallback);Application app=new Application(null,ApplicationStatus.SAVED,null,false,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);ReflectionTestUtils.setField(app,"id",9L);ReflectionTestUtils.setField(app,"resumeMaterial",selected);ApplicationPreparationSession session=mock(ApplicationPreparationSession.class);when(session.getApplication()).thenReturn(app);when(session.getId()).thenReturn(4L);when(sessions.findByIdAndApplicationId(4L,9L)).thenReturn(Optional.of(session));when(plans.findBySessionId(4L)).thenReturn(Optional.empty());when(plans.saveAndFlush(any())).thenAnswer(i->{ApprovedMaterialPlan p=i.getArgument(0);ReflectionTestUtils.setField(p,"id",11L);ReflectionTestUtils.setField(p,"createdAt",java.time.OffsetDateTime.now());return p;});var result=service.create(9L,4L);assertThat(result.materialId()).isEqualTo(7L);assertThat(result.authoritySource()).isEqualTo("APPLICATION_SELECTION");assertThat(result.toString()).doesNotContain("storage-key");}
 @Test void noSelectionSurfacesUserDecision(){Application app=new Application(null,ApplicationStatus.SAVED,null,false,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);ApplicationPreparationSession session=mock(ApplicationPreparationSession.class);when(session.getApplication()).thenReturn(app);when(sessions.findByIdAndApplicationId(4L,9L)).thenReturn(Optional.of(session));when(plans.findBySessionId(4L)).thenReturn(Optional.empty());when(profiles.findByProfileKey(ApplicantProfile.PRIMARY_PROFILE_KEY)).thenReturn(Optional.empty());assertThat(service.create(9L,4L).userSelectionRequired()).isTrue();verify(plans,never()).save(any());}
 private ApplicantProfile profile(){ApplicantProfile p=new ApplicantProfile("A","B",null,"a@b.com",null,null,null,null,null,null,null,null,null,RemoteType.UNKNOWN,null,"USD",null,null);ReflectionTestUtils.setField(p,"id",3L);return p;}
 private CareerMaterial material(ApplicantProfile p,Long id,String name){CareerMaterial m=mock(CareerMaterial.class);lenient().when(m.getId()).thenReturn(id);lenient().when(m.getApplicantProfile()).thenReturn(p);lenient().when(m.getMaterialType()).thenReturn(CareerMaterial.MaterialType.RESUME);lenient().when(m.getDisplayName()).thenReturn(name);lenient().when(m.getOriginalFilename()).thenReturn(name+".pdf");lenient().when(m.getMimeType()).thenReturn("application/pdf");lenient().when(m.isActive()).thenReturn(true);lenient().when(m.getStorageKey()).thenReturn("storage-key");return m;}
}
