CREATE TABLE application_question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_question_id BIGINT NOT NULL REFERENCES application_questions(id) ON DELETE CASCADE,
    external_option_id VARCHAR(200),
    option_value VARCHAR(1000) NOT NULL,
    option_label VARCHAR(1000) NOT NULL,
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE(application_question_id, option_value)
);

INSERT INTO application_question_options(
    application_question_id, option_value, option_label, display_order
)
SELECT id, allowed_values, allowed_values, 0
FROM application_questions
WHERE NULLIF(TRIM(allowed_values), '') IS NOT NULL;

ALTER TABLE application_questions DROP COLUMN allowed_values;

CREATE TABLE form_observation_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_target_id BIGINT NOT NULL REFERENCES application_form_targets(id) ON DELETE CASCADE,
    sequence_number INTEGER NOT NULL,
    snapshot_fingerprint VARCHAR(64) NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(form_target_id, sequence_number)
);

CREATE TABLE observed_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL REFERENCES form_observation_snapshots(id) ON DELETE CASCADE,
    external_question_id VARCHAR(200) NOT NULL,
    question_text VARCHAR(1000) NOT NULL,
    answer_type VARCHAR(30) NOT NULL,
    required BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL,
    question_fingerprint VARCHAR(64) NOT NULL,
    UNIQUE(snapshot_id, external_question_id)
);

CREATE TABLE observed_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observed_question_id BIGINT NOT NULL REFERENCES observed_questions(id) ON DELETE CASCADE,
    external_option_id VARCHAR(200),
    option_value VARCHAR(1000) NOT NULL,
    option_label VARCHAR(1000) NOT NULL,
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    UNIQUE(observed_question_id, option_value)
);

CREATE INDEX ix_form_observation_snapshots_target_sequence
    ON form_observation_snapshots(form_target_id, sequence_number DESC);
CREATE INDEX ix_observed_questions_snapshot_order
    ON observed_questions(snapshot_id, display_order, external_question_id);
CREATE INDEX ix_observed_options_question_order
    ON observed_options(observed_question_id, display_order, option_value);
