CREATE TABLE approved_field_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL UNIQUE REFERENCES application_preparation_sessions(id) ON DELETE CASCADE,
    generated_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approved_field_plan_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL REFERENCES approved_field_plans(id) ON DELETE CASCADE,
    canonical_key VARCHAR(80) NOT NULL,
    answer_type VARCHAR(20) NOT NULL,
    text_value TEXT,
    boolean_value BOOLEAN,
    number_value NUMERIC(14,2),
    value_source VARCHAR(30) NOT NULL,
    source_record_id BIGINT,
    source_verified_at TIMESTAMPTZ NOT NULL,
    display_order INTEGER NOT NULL,
    UNIQUE(plan_id, canonical_key)
);

CREATE TABLE field_preparation_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_item_id BIGINT NOT NULL UNIQUE REFERENCES approved_field_plan_items(id) ON DELETE CASCADE,
    outcome VARCHAR(20) NOT NULL,
    safe_message VARCHAR(1000),
    prepared_at TIMESTAMPTZ,
    recorded_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_approved_field_plan_items_plan_order
    ON approved_field_plan_items(plan_id, display_order, id);

CREATE INDEX ix_field_preparation_results_recorded
    ON field_preparation_results(recorded_at, id);
