CREATE TABLE preparation_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL UNIQUE REFERENCES application_preparation_sessions(id) ON DELETE CASCADE,
    snapshot_hash VARCHAR(64) NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE preparation_review_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL REFERENCES preparation_reviews(id) ON DELETE CASCADE,
    canonical_key VARCHAR(80) NOT NULL,
    answer_type VARCHAR(20) NOT NULL,
    text_value TEXT,
    boolean_value BOOLEAN,
    number_value NUMERIC(14,2),
    value_source VARCHAR(30) NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    safe_message VARCHAR(1000),
    prepared_at TIMESTAMPTZ,
    display_order INTEGER NOT NULL,
    UNIQUE(review_id, canonical_key)
);

CREATE TABLE preparation_review_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL REFERENCES preparation_reviews(id) ON DELETE CASCADE,
    application_question_id BIGINT NOT NULL REFERENCES application_questions(id),
    category VARCHAR(20) NOT NULL,
    canonical_key VARCHAR(80),
    question_text VARCHAR(1000) NOT NULL,
    answer_type VARCHAR(30) NOT NULL,
    required BOOLEAN NOT NULL,
    question_status VARCHAR(30) NOT NULL,
    display_order INTEGER NOT NULL,
    UNIQUE(review_id, application_question_id)
);

CREATE TABLE preparation_review_screenshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL REFERENCES preparation_reviews(id) ON DELETE CASCADE,
    reference VARCHAR(1000) NOT NULL,
    page_key VARCHAR(200),
    captured_at TIMESTAMPTZ NOT NULL,
    display_order INTEGER NOT NULL,
    UNIQUE(review_id, reference)
);

CREATE INDEX ix_preparation_review_fields_order ON preparation_review_fields(review_id, display_order, id);
CREATE INDEX ix_preparation_review_questions_order ON preparation_review_questions(review_id, category, display_order, id);
CREATE INDEX ix_preparation_review_screenshots_order ON preparation_review_screenshots(review_id, display_order, id);
