CREATE TABLE observed_question_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_target_id BIGINT NOT NULL REFERENCES application_form_targets(id) ON DELETE CASCADE,
    external_question_id VARCHAR(200) NOT NULL,
    canonical_question_key VARCHAR(80),
    mapping_source VARCHAR(30),
    mapping_state VARCHAR(20) NOT NULL,
    confidence NUMERIC(4,3),
    user_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(form_target_id, external_question_id)
);

CREATE TABLE observed_question_mapping_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_id BIGINT NOT NULL REFERENCES observed_question_mappings(id) ON DELETE CASCADE,
    event_type VARCHAR(20) NOT NULL,
    previous_canonical_key VARCHAR(80),
    canonical_question_key VARCHAR(80),
    mapping_source VARCHAR(30),
    confidence NUMERIC(4,3),
    user_confirmed BOOLEAN NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_observed_question_mappings_target
    ON observed_question_mappings(form_target_id, external_question_id);
CREATE INDEX ix_observed_question_mapping_history_mapping
    ON observed_question_mapping_history(mapping_id, occurred_at, id);
CREATE UNIQUE INDEX ux_application_questions_external_identity
    ON application_questions(application_id, external_question_key)
    WHERE external_question_key IS NOT NULL;
