CREATE TABLE career_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_profile_id BIGINT NOT NULL REFERENCES applicant_profiles(id),
    material_type VARCHAR(30) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    storage_key VARCHAR(255) NOT NULL UNIQUE,
    mime_type VARCHAR(120) NOT NULL,
    file_size BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT,
    target_job_family VARCHAR(120),
    target_seniority VARCHAR(80),
    version_label VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX ix_career_materials_profile_active
    ON career_materials(applicant_profile_id, active, display_name, id);

ALTER TABLE applicant_profiles
    ADD COLUMN default_resume_material_id BIGINT
        REFERENCES career_materials(id);

ALTER TABLE applications
    ADD COLUMN resume_material_id BIGINT
        REFERENCES career_materials(id);

CREATE INDEX ix_applications_resume_material
    ON applications(resume_material_id);

CREATE TABLE approved_material_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL UNIQUE
        REFERENCES application_preparation_sessions(id) ON DELETE CASCADE,
    material_type VARCHAR(30) NOT NULL,
    career_material_id BIGINT NOT NULL REFERENCES career_materials(id),
    authority_source VARCHAR(40) NOT NULL,
    display_filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
