CREATE TABLE application_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL UNIQUE REFERENCES applications(id) ON DELETE CASCADE,
    lock_state VARCHAR(30) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE application_lock_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    previous_lock VARCHAR(30),
    new_lock VARCHAR(30) NOT NULL,
    source VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason TEXT
);

INSERT INTO application_locks(application_id, lock_state, reason)
SELECT id,
    CASE WHEN status IN ('APPLIED','PHONE_SCREEN','INTERVIEW_ONE','INTERVIEW_TWO','OFFER','REJECTED')
         THEN 'SUBMITTED' ELSE 'NOT_SUBMITTED' END,
    'Deterministic lifecycle bootstrap'
FROM applications;

INSERT INTO application_lock_history(application_id, previous_lock, new_lock, source, reason)
SELECT application_id, NULL, lock_state, 'SYSTEM', 'Initialized from application lifecycle'
FROM application_locks;

CREATE INDEX ix_application_lock_history_application_time
    ON application_lock_history(application_id, occurred_at, id);
