ALTER TABLE preparation_session_events
    ADD COLUMN provider_failure_code VARCHAR(80);

ALTER TABLE preparation_session_events
    ADD CONSTRAINT ck_preparation_event_provider_failure_code
    CHECK (
        provider_failure_code IS NULL OR provider_failure_code IN (
            'ASHBY_FORM_ENTRY_NOT_FOUND',
            'ASHBY_FORM_NOT_OPENED',
            'ASHBY_APPLICATION_ROOT_NOT_FOUND',
            'ASHBY_STABLE_FIELD_ID_MISSING',
            'ASHBY_UNSUPPORTED_LAYOUT',
            'ASHBY_OBSERVATION_PERSIST_FAILED'
        )
    );

CREATE TABLE observed_material_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL REFERENCES form_observation_snapshots(id) ON DELETE CASCADE,
    external_field_id VARCHAR(200) NOT NULL,
    material_type VARCHAR(30) NOT NULL,
    field_label VARCHAR(1000) NOT NULL,
    required BOOLEAN NOT NULL,
    accept_types VARCHAR(1000),
    display_order INTEGER NOT NULL,
    page_key VARCHAR(200) NOT NULL,
    UNIQUE(snapshot_id, external_field_id)
);

CREATE INDEX ix_observed_material_requirements_snapshot_order
    ON observed_material_requirements(snapshot_id, display_order, external_field_id);
