CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    website_url VARCHAR(500),
    careers_url VARCHAR(500),
    industry VARCHAR(150),
    company_type VARCHAR(100),
    mission TEXT,
    products TEXT,
    tech_stack TEXT,
    remote_policy TEXT,
    salary_notes TEXT,
    general_notes TEXT,
    dream_company BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ux_companies_name_lower
    ON companies (LOWER(name));

CREATE INDEX ix_companies_dream_company
    ON companies (dream_company);