CREATE TABLE job_opportunities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,

    position_title VARCHAR(200) NOT NULL,
    department VARCHAR(150),
    location VARCHAR(200),

    remote_type VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
    employment_type VARCHAR(50),

    salary_min NUMERIC(12, 2),
    salary_max NUMERIC(12, 2),
    salary_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    salary_notes TEXT,

    application_url VARCHAR(1000),
    source VARCHAR(150),
    date_posted DATE,
    closing_date DATE,

    priority SMALLINT NOT NULL DEFAULT 3,
    match_score NUMERIC(3, 1),

    job_description TEXT,
    notes TEXT,

    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_job_opportunities_remote_type
        CHECK (
            remote_type IN (
                'REMOTE',
                'HYBRID',
                'ONSITE',
                'UNKNOWN'
            )
        ),

    CONSTRAINT ck_job_opportunities_priority
        CHECK (priority BETWEEN 1 AND 5),

    CONSTRAINT ck_job_opportunities_match_score
        CHECK (
            match_score IS NULL
            OR match_score BETWEEN 0 AND 10
        ),

    CONSTRAINT ck_job_opportunities_salary_range
        CHECK (
            salary_min IS NULL
            OR salary_max IS NULL
            OR salary_max >= salary_min
        )
);

CREATE INDEX ix_job_opportunities_company_id
    ON job_opportunities(company_id);

CREATE INDEX ix_job_opportunities_position_title
    ON job_opportunities(LOWER(position_title));

CREATE INDEX ix_job_opportunities_priority
    ON job_opportunities(priority);

CREATE INDEX ix_job_opportunities_date_posted
    ON job_opportunities(date_posted);


CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    job_opportunity_id BIGINT NOT NULL
        REFERENCES job_opportunities(id)
        ON DELETE CASCADE,

    status VARCHAR(40) NOT NULL DEFAULT 'SAVED',

    resume_version VARCHAR(100),
    cover_letter_needed BOOLEAN NOT NULL DEFAULT FALSE,

    portfolio_link VARCHAR(1000),
    github_link VARCHAR(1000),

    projects_to_highlight TEXT,
    skills_to_emphasize TEXT,
    interview_topics TEXT,

    recruiter_name VARCHAR(200),
    recruiter_email VARCHAR(320),

    application_date DATE,
    follow_up_date DATE,

    phone_screen_at TIMESTAMP WITH TIME ZONE,
    interview_one_at TIMESTAMP WITH TIME ZONE,
    interview_two_at TIMESTAMP WITH TIME ZONE,
    offer_at TIMESTAMP WITH TIME ZONE,
    rejected_at TIMESTAMP WITH TIME ZONE,

    notes TEXT,

    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ux_applications_job_opportunity
        UNIQUE(job_opportunity_id),

    CONSTRAINT ck_applications_status
        CHECK (
            status IN (
                'SAVED',
                'PREPARING',
                'APPLIED',
                'PHONE_SCREEN',
                'INTERVIEW_ONE',
                'INTERVIEW_TWO',
                'OFFER',
                'REJECTED',
                'WITHDRAWN',
                'CLOSED'
            )
        )
);

CREATE INDEX ix_applications_status
    ON applications(status);

CREATE INDEX ix_applications_application_date
    ON applications(application_date);

CREATE INDEX ix_applications_follow_up_date
    ON applications(follow_up_date);