CREATE TABLE import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_filename VARCHAR(255) NOT NULL,
    format VARCHAR(20) NOT NULL,
    schema_version VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE,
    total_row_count INTEGER NOT NULL,
    selected_row_count INTEGER NOT NULL,
    created_row_count INTEGER NOT NULL DEFAULT 0,
    warning_created_row_count INTEGER NOT NULL DEFAULT 0,
    skipped_duplicate_row_count INTEGER NOT NULL DEFAULT 0,
    failed_row_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_import_batches_counts_nonnegative CHECK (
        total_row_count >= 0 AND selected_row_count >= 0
        AND created_row_count >= 0 AND warning_created_row_count >= 0
        AND skipped_duplicate_row_count >= 0 AND failed_row_count >= 0
    )
);

CREATE TABLE import_batch_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id BIGINT NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
    source_row_number INTEGER NOT NULL,
    outcome VARCHAR(40) NOT NULL,
    company_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    job_opportunity_id BIGINT REFERENCES job_opportunities(id) ON DELETE SET NULL,
    application_id BIGINT REFERENCES applications(id) ON DELETE SET NULL,
    duplicate_job_opportunity_id BIGINT REFERENCES job_opportunities(id) ON DELETE SET NULL,
    warnings TEXT,
    errors TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_import_batch_source_row UNIQUE (import_batch_id, source_row_number),
    CONSTRAINT ck_import_batch_rows_source_row CHECK (source_row_number >= 2),
    CONSTRAINT ck_import_batch_rows_outcome CHECK (
        outcome IN (
            'CREATED', 'CREATED_WITH_WARNING', 'SKIPPED_DUPLICATE',
            'FAILED_VALIDATION', 'FAILED_PERSISTENCE'
        )
    )
);

CREATE INDEX ix_import_batch_rows_job
    ON import_batch_rows(job_opportunity_id);
