CREATE TABLE applicant_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    profile_key VARCHAR(40) NOT NULL,

    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    preferred_name VARCHAR(100),
    email VARCHAR(320) NOT NULL,
    phone VARCHAR(50),
    city VARCHAR(100),
    state_region VARCHAR(100),
    country VARCHAR(100),
    postal_code VARCHAR(20),

    portfolio_url VARCHAR(1000),
    github_url VARCHAR(1000),
    linkedin_url VARCHAR(1000),

    default_resume_version VARCHAR(100),
    preferred_work_arrangement VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
    minimum_salary NUMERIC(12, 2),
    salary_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    willing_to_relocate BOOLEAN,
    willing_to_travel BOOLEAN,

    verified BOOLEAN NOT NULL DEFAULT FALSE,
    last_verified_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ux_applicant_profiles_profile_key UNIQUE(profile_key),
    CONSTRAINT ck_applicant_profiles_profile_key
        CHECK (profile_key = 'PRIMARY'),
    CONSTRAINT ck_applicant_profiles_work_arrangement
        CHECK (
            preferred_work_arrangement IN (
                'REMOTE', 'HYBRID', 'ONSITE', 'UNKNOWN'
            )
        ),
    CONSTRAINT ck_applicant_profiles_minimum_salary
        CHECK (minimum_salary IS NULL OR minimum_salary >= 0),
    CONSTRAINT ck_applicant_profiles_salary_currency
        CHECK (salary_currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_applicant_profiles_verification
        CHECK (
            (verified = TRUE AND last_verified_at IS NOT NULL)
            OR (verified = FALSE AND last_verified_at IS NULL)
        )
);
