CREATE TABLE approved_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_key VARCHAR(80) NOT NULL,
    representative_question VARCHAR(500) NOT NULL,
    answer_type VARCHAR(20) NOT NULL,
    text_value TEXT,
    boolean_value BOOLEAN,
    number_value NUMERIC(14, 2),
    classification VARCHAR(30) NOT NULL,
    reusable BOOLEAN NOT NULL DEFAULT FALSE,
    user_approved BOOLEAN NOT NULL DEFAULT FALSE,
    approved_at TIMESTAMP WITH TIME ZONE,
    last_used_at TIMESTAMP WITH TIME ZONE,
    answer_source VARCHAR(30) NOT NULL DEFAULT 'MANUAL',
    profile_field VARCHAR(40),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ux_approved_answers_canonical_key UNIQUE(canonical_key),
    CONSTRAINT ck_approved_answers_canonical_key
        CHECK (canonical_key ~ '^[a-z][a-z0-9_]{2,79}$'),
    CONSTRAINT ck_approved_answers_type
        CHECK (answer_type IN ('TEXT', 'BOOLEAN', 'NUMBER')),
    CONSTRAINT ck_approved_answers_classification
        CHECK (
            classification IN (
                'VERIFIED_REUSABLE', 'CONTEXTUAL', 'SENSITIVE', 'UNKNOWN'
            )
        ),
    CONSTRAINT ck_approved_answers_source
        CHECK (answer_source IN ('MANUAL', 'APPLICANT_PROFILE')),
    CONSTRAINT ck_approved_answers_profile_field
        CHECK (
            profile_field IS NULL
            OR profile_field IN (
                'WILLING_TO_RELOCATE',
                'WILLING_TO_TRAVEL',
                'MINIMUM_SALARY'
            )
        ),
    CONSTRAINT ck_approved_answers_approval
        CHECK (
            (user_approved = TRUE AND approved_at IS NOT NULL)
            OR (user_approved = FALSE AND approved_at IS NULL)
        ),
    CONSTRAINT ck_approved_answers_reusable
        CHECK (
            reusable = FALSE
            OR classification = 'VERIFIED_REUSABLE'
        ),
    CONSTRAINT ck_approved_answers_value_source
        CHECK (
            (
                answer_source = 'APPLICANT_PROFILE'
                AND profile_field IS NOT NULL
                AND text_value IS NULL
                AND boolean_value IS NULL
                AND number_value IS NULL
            )
            OR
            (
                answer_source = 'MANUAL'
                AND profile_field IS NULL
                AND (
                    (answer_type = 'TEXT' AND text_value IS NOT NULL
                        AND boolean_value IS NULL AND number_value IS NULL)
                    OR
                    (answer_type = 'BOOLEAN' AND text_value IS NULL
                        AND boolean_value IS NOT NULL AND number_value IS NULL)
                    OR
                    (answer_type = 'NUMBER' AND text_value IS NULL
                        AND boolean_value IS NULL AND number_value IS NOT NULL)
                )
            )
        )
);
