CREATE TABLE application_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    previous_status VARCHAR(40),
    new_status VARCHAR(40) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    source VARCHAR(20) NOT NULL,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_application_status_history_application
        FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    CONSTRAINT ck_application_status_history_source
        CHECK (source IN ('USER', 'IMPORT', 'SYSTEM', 'AUTOMATION')),
    CONSTRAINT ck_application_status_history_transition
        CHECK (previous_status IS NULL OR previous_status <> new_status)
);

CREATE INDEX ix_application_status_history_application_occurred
    ON application_status_history(application_id, occurred_at, id);
