CREATE TABLE question_templates (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 job_family VARCHAR(40) NOT NULL, seniority VARCHAR(30), canonical_question_key VARCHAR(80) NOT NULL,
 representative_question VARCHAR(500) NOT NULL, answer_type VARCHAR(30) NOT NULL,
 classification VARCHAR(30) NOT NULL, required_by_default BOOLEAN NOT NULL DEFAULT FALSE,
 common BOOLEAN NOT NULL DEFAULT TRUE, active BOOLEAN NOT NULL DEFAULT TRUE, notes TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(job_family, seniority, canonical_question_key)
);
CREATE UNIQUE INDEX ux_question_templates_broad ON question_templates(job_family, canonical_question_key) WHERE seniority IS NULL;

CREATE TABLE application_questions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
 template_id BIGINT REFERENCES question_templates(id), external_question_key VARCHAR(200),
 canonical_question_key VARCHAR(80), question_text VARCHAR(1000) NOT NULL,
 answer_type VARCHAR(30) NOT NULL, required BOOLEAN NOT NULL DEFAULT FALSE,
 allowed_values TEXT, classification VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL,
 proposed_answer TEXT, approved_answer TEXT, approved_answer_id BIGINT REFERENCES approved_answers(id) ON DELETE SET NULL,
 source VARCHAR(20) NOT NULL, notes TEXT, answered_at TIMESTAMPTZ, reviewed_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(application_id, template_id)
);
CREATE INDEX ix_application_questions_application_status ON application_questions(application_id, status, id);

INSERT INTO question_templates(job_family, seniority, canonical_question_key, representative_question, answer_type, classification, required_by_default, common) VALUES
('SOFTWARE_ENGINEER',NULL,'github_url','What is your GitHub profile URL?','TEXT','VERIFIED_REUSABLE',FALSE,TRUE),
('SOFTWARE_ENGINEER',NULL,'years_relevant_experience','How many years of relevant experience do you have?','NUMBER','UNKNOWN',FALSE,TRUE),
('SOFTWARE_ENGINEER',NULL,'willing_to_relocate','Are you willing to relocate?','BOOLEAN','VERIFIED_REUSABLE',FALSE,TRUE),
('SOFTWARE_ENGINEER',NULL,'salary_expectation','What is your salary expectation?','NUMBER','VERIFIED_REUSABLE',FALSE,TRUE),
('SOFTWARE_ENGINEER',NULL,'why_this_role','Why are you interested in this role?','TEXT','CONTEXTUAL',FALSE,TRUE),
('FULL_STACK_ENGINEER',NULL,'years_react_experience','How many years of React experience do you have?','NUMBER','UNKNOWN',FALSE,TRUE),
('FRONTEND_ENGINEER',NULL,'years_typescript_experience','How many years of TypeScript experience do you have?','NUMBER','UNKNOWN',FALSE,TRUE),
('BACKEND_ENGINEER',NULL,'years_backend_api_experience','How many years of backend/API experience do you have?','NUMBER','UNKNOWN',FALSE,TRUE),
('SOFTWARE_ENGINEER','SENIOR','required_onsite_schedule','Can you meet the required onsite schedule?','BOOLEAN','KNOCKOUT',FALSE,TRUE);
