CREATE TABLE application_automation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL UNIQUE REFERENCES applications(id) ON DELETE CASCADE,
    state VARCHAR(40) NOT NULL DEFAULT 'NOT_APPROVED',
    submission_mode VARCHAR(40) NOT NULL DEFAULT 'PREPARE_ONLY',
    ats_type VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
    approved_for_prep_at TIMESTAMPTZ,
    ready_for_review_at TIMESTAMPTZ,
    approved_to_submit_at TIMESTAMPTZ,
    blocked_at TIMESTAMPTZ,
    block_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO application_automation(application_id)
SELECT id FROM applications;

CREATE TABLE application_automation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_automation_id BIGINT NOT NULL REFERENCES application_automation(id) ON DELETE CASCADE,
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    previous_state VARCHAR(40),
    new_state VARCHAR(40) NOT NULL,
    source VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    reason TEXT
);

CREATE INDEX ix_automation_history_application_time
    ON application_automation_history(application_id, occurred_at, id);
