ALTER TABLE job_opportunities
    ADD COLUMN normalized_application_url VARCHAR(1000);

UPDATE job_opportunities
SET normalized_application_url = NULLIF(TRIM(application_url), '')
WHERE application_url IS NOT NULL;

CREATE INDEX ix_job_opportunities_normalized_application_url
    ON job_opportunities(normalized_application_url)
    WHERE normalized_application_url IS NOT NULL;

CREATE TABLE application_form_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL UNIQUE REFERENCES applications(id) ON DELETE CASCADE,
    normalized_form_url VARCHAR(1000) NOT NULL,
    external_requisition_id VARCHAR(200),
    external_form_key VARCHAR(200),
    identity_source VARCHAR(30) NOT NULL,
    last_confirmed_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE application_preparation_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    form_target_id BIGINT NOT NULL REFERENCES application_form_targets(id),
    previous_session_id BIGINT REFERENCES application_preparation_sessions(id),
    state VARCHAR(40) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    last_progress_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ux_preparation_sessions_one_active_application
    ON application_preparation_sessions(application_id)
    WHERE state IN (
        'INITIALIZED', 'OPENING', 'COLLECTING_QUESTIONS',
        'WAITING_FOR_USER', 'PREPARING_FIELDS'
    );

CREATE INDEX ix_preparation_sessions_application_created
    ON application_preparation_sessions(application_id, created_at DESC, id DESC);

CREATE TABLE preparation_session_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES application_preparation_sessions(id) ON DELETE CASCADE,
    event_type VARCHAR(50) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    retryable BOOLEAN NOT NULL DEFAULT FALSE,
    safe_user_message VARCHAR(1000) NOT NULL,
    page_key VARCHAR(200),
    question_key VARCHAR(200)
);

CREATE INDEX ix_preparation_session_events_session_time
    ON preparation_session_events(session_id, occurred_at, id);
