package com.chengukargbo.careeros.questions;
import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.chengukargbo.careeros.applications.*; import com.chengukargbo.careeros.answers.*; import com.chengukargbo.careeros.answers.dto.ApprovedAnswerResponse; import com.chengukargbo.careeros.common.exception.BusinessValidationException; import com.chengukargbo.careeros.questions.QuestionDtos.*; import com.chengukargbo.careeros.questions.QuestionEnums.*;
import com.chengukargbo.careeros.automation.ApplicationAutomationService;
@Service @Transactional
public class QuestionQueueService {
 private final QuestionTemplateRepository templates; private final ApplicationQuestionRepository questions; private final ApplicationRepository applications; private final ApprovedAnswerRepository answers; private final ApprovedAnswerService answerService; private final ApplicationAutomationService automationService;
 public QuestionQueueService(QuestionTemplateRepository t,ApplicationQuestionRepository q,ApplicationRepository a,ApprovedAnswerRepository ar,ApprovedAnswerService as,ApplicationAutomationService automation){templates=t;questions=q;applications=a;answers=ar;answerService=as;automationService=automation;}
 @Transactional(readOnly=true) public List<TemplateResponse> templates(JobFamily family,Seniority seniority){return templates.findByJobFamilyAndActiveTrueOrderByCanonicalQuestionKeyAsc(family).stream().filter(t->t.getSeniority()==null||t.getSeniority()==seniority).map(TemplateResponse::from).toList();}
 @Transactional(readOnly=true) public List<QuestionResponse> all(Long applicationId){return (applicationId==null?questions.findAllByOrderByApplicationIdAscIdAsc():questions.findByApplicationIdOrderByIdAsc(applicationId)).stream().map(QuestionResponse::from).toList();}
 public QuestionResponse manual(ManualRequest r){Application a=application(r.applicationId());ApplicationQuestion q=new ApplicationQuestion(a,null,normalize(r.canonicalQuestionKey()),r.questionText().trim(),r.answerType(),r.required(),r.classification(),Source.MANUAL);QuestionResponse response=QuestionResponse.from(questions.saveAndFlush(q));automationService.recalculate(a.getId());return response;}
 public List<QuestionResponse> addTemplates(AddTemplatesRequest r){Application a=application(r.applicationId());List<QuestionResponse> out=new ArrayList<>();for(Long id:r.templateIds()){QuestionTemplate t=templates.findById(id).orElseThrow(()->new BusinessValidationException("Question template not found: "+id));if(questions.existsByApplicationIdAndTemplateId(a.getId(),id))continue;ApplicationQuestion q=new ApplicationQuestion(a,t,t.getCanonicalQuestionKey(),t.getRepresentativeQuestion(),t.getAnswerType(),t.isRequiredByDefault(),t.getClassification(),Source.TEMPLATE);suggestExact(q);out.add(QuestionResponse.from(questions.saveAndFlush(q)));}automationService.recalculate(a.getId());return out;}
 public QuestionResponse answer(Long id,String value){ApplicationQuestion q=find(id);if(value==null||value.isBlank())throw new BusinessValidationException("Answer is required");q.answer(value.trim());QuestionResponse response=QuestionResponse.from(questions.saveAndFlush(q));automationService.recalculate(q.getApplication().getId());return response;}
 public QuestionResponse approve(Long id){ApplicationQuestion q=find(id);try{q.approve();}catch(IllegalStateException e){throw new BusinessValidationException(e.getMessage());}QuestionResponse response=QuestionResponse.from(questions.saveAndFlush(q));automationService.recalculate(q.getApplication().getId());return response;}
 public QuestionResponse reject(Long id){ApplicationQuestion q=find(id);q.rejectSuggestion();QuestionResponse response=QuestionResponse.from(questions.saveAndFlush(q));automationService.recalculate(q.getApplication().getId());return response;}
 public QuestionResponse block(Long id,boolean blocked){ApplicationQuestion q=find(id);if(blocked)q.block();else q.unblock();QuestionResponse response=QuestionResponse.from(questions.saveAndFlush(q));automationService.recalculate(q.getApplication().getId());return response;}
 public QuestionResponse link(Long id,Long answerId){ApplicationQuestion q=find(id);ApprovedAnswer a=answers.findById(answerId).orElseThrow(()->new BusinessValidationException("Approved answer not found"));if(q.getCanonicalQuestionKey()==null||!q.getCanonicalQuestionKey().equals(a.getCanonicalKey()))throw new BusinessValidationException("Approved answer canonical key must exactly match");ApprovedAnswerResponse linked=answerService.findAll().stream().filter(x->x.id().equals(answerId)&&x.userApproved()&&x.authorityAvailable()&&x.classification()!=AnswerClassification.UNKNOWN).findFirst().orElseThrow(()->new BusinessValidationException("Approved answer is not currently available for review"));q.suggest(a,display(linked));return QuestionResponse.from(questions.saveAndFlush(q));}
 private void suggestExact(ApplicationQuestion q){if(q.getCanonicalQuestionKey()==null)return;answerService.findAll().stream().filter(a->a.canonicalKey().equals(q.getCanonicalQuestionKey())&&a.effectiveReusable()).findFirst().ifPresent(a->answers.findById(a.id()).ifPresent(entity->q.suggest(entity,display(a))));}
 private String display(ApprovedAnswerResponse a){if(a.resolvedTextValue()!=null)return a.resolvedTextValue();if(a.resolvedBooleanValue()!=null)return a.resolvedBooleanValue()?"Yes":"No";if(a.resolvedNumberValue()!=null)return a.resolvedNumberValue().toPlainString()+(a.resolvedCurrency()==null?"":" "+a.resolvedCurrency());return null;}
 private Application application(Long id){return applications.findById(id).orElseThrow(()->new ApplicationNotFoundException(id));} private ApplicationQuestion find(Long id){return questions.findById(id).orElseThrow(()->new BusinessValidationException("Application question not found: "+id));} private String normalize(String s){return s==null||s.isBlank()?null:s.trim().toLowerCase(Locale.ROOT);}
}
