package com.chengukargbo.careeros.questions;
import java.time.OffsetDateTime; import java.util.List; import com.chengukargbo.careeros.questions.QuestionEnums.*;
import jakarta.validation.constraints.*;
public final class QuestionDtos {private QuestionDtos(){}
 public record TemplateResponse(Long id,JobFamily jobFamily,Seniority seniority,String canonicalQuestionKey,String representativeQuestion,AnswerType answerType,Classification classification,boolean requiredByDefault,boolean common){static TemplateResponse from(QuestionTemplate t){return new TemplateResponse(t.getId(),t.getJobFamily(),t.getSeniority(),t.getCanonicalQuestionKey(),t.getRepresentativeQuestion(),t.getAnswerType(),t.getClassification(),t.isRequiredByDefault(),t.isCommon());}}
 public record OptionResponse(Long id,String externalOptionId,String value,String label,int displayOrder,boolean active){static OptionResponse from(ApplicationQuestionOption o){return new OptionResponse(o.getId(),o.getExternalOptionId(),o.getValue(),o.getLabel(),o.getDisplayOrder(),o.isActive());}}
 public record QuestionResponse(Long id,Long applicationId,Long jobOpportunityId,String companyName,String positionTitle,String lifecycleStatus,String canonicalQuestionKey,String questionText,AnswerType answerType,boolean required,List<OptionResponse> options,Classification classification,Status status,String proposedAnswer,String approvedAnswer,Long approvedAnswerId,Source source,String notes,OffsetDateTime answeredAt,OffsetDateTime reviewedAt,OffsetDateTime createdAt,OffsetDateTime updatedAt){static QuestionResponse from(ApplicationQuestion q){var j=q.getApplication().getJobOpportunity();return new QuestionResponse(q.getId(),q.getApplication().getId(),j.getId(),j.getCompany()==null?null:j.getCompany().getName(),j.getPositionTitle(),q.getApplication().getStatus().name(),q.getCanonicalQuestionKey(),q.getQuestionText(),q.getAnswerType(),q.isRequired(),q.getOptions().stream().map(OptionResponse::from).toList(),q.getClassification(),q.getStatus(),q.getProposedAnswer(),q.getApprovedAnswer(),q.getApprovedAnswerLink()==null?null:q.getApprovedAnswerLink().getId(),q.getSource(),q.getNotes(),q.getAnsweredAt(),q.getReviewedAt(),q.getCreatedAt(),q.getUpdatedAt());}}
 public record ManualRequest(@NotNull Long applicationId,@Pattern(regexp="^[a-z][a-z0-9_]{2,79}$") String canonicalQuestionKey,@NotBlank @Size(max=1000) String questionText,@NotNull AnswerType answerType,boolean required,@NotNull Classification classification,@Size(max=5000) String notes){}
 public record AddTemplatesRequest(@NotNull Long applicationId,@NotEmpty List<@NotNull Long> templateIds){}
 public record AnswerRequest(@NotBlank @Size(max=10000) String answer){}
 public record LinkRequest(@NotNull Long approvedAnswerId){}
}
