import { useMemo, useState } from "react";
import { automationAction, type ApplicationAutomation } from "../api/applicationsApi";
import type { ApplicationStatus } from "../types/application";
import type { ApplicationTrackerRow } from "../types/applicationTracker";
import type { RemoteType } from "../../jobs/types/job";

interface Props { rows:ApplicationTrackerRow[]; deletingId:number|null; onEdit:(row:ApplicationTrackerRow)=>void; onDelete:(row:ApplicationTrackerRow)=>Promise<void>; onAddApplication:(id:number)=>void; onMarkApplied:(row:ApplicationTrackerRow)=>void }
type AutomationState=ApplicationAutomation["state"];
const statusLabels:Record<ApplicationStatus,string>={SAVED:"Saved",PREPARING:"Preparing",APPLIED:"Applied",PHONE_SCREEN:"Phone Screen",INTERVIEW_ONE:"Interview 1",INTERVIEW_TWO:"Interview 2",OFFER:"Offer",REJECTED:"Rejected",WITHDRAWN:"Withdrawn",CLOSED:"Closed"};
const automationLabels:Record<AutomationState,string>={NOT_APPROVED:"Not approved",APPROVED_FOR_PREP:"Approved",NEEDS_ANSWERS:"Needs answers",BLOCKED:"Blocked",READY_FOR_REVIEW:"Ready for review",APPROVED_TO_SUBMIT:"Approved to submit"};
const remoteLabels:Record<RemoteType,string>={REMOTE:"Remote",HYBRID:"Hybrid",ONSITE:"Onsite",UNKNOWN:"Unknown"};
const lockLabels={NOT_SUBMITTED:"Not Submitted",SUBMITTED:"Submitted",ARCHIVED:"Archived",TESTING:"Testing"} as const;
function formatDate(value:string|null|undefined){if(!value)return "—";return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(value));}
function locked(row:ApplicationTrackerRow){return row.lockState==="SUBMITTED"||row.lockState==="ARCHIVED";}

export default function ApplicationList({rows,deletingId,onEdit,onDelete,onAddApplication,onMarkApplied}:Props){
 const initial=useMemo(()=>Object.fromEntries(rows.filter(r=>r.applicationId!==null).map(r=>[r.applicationId!,r.automationState??"NOT_APPROVED"])),[rows]);
 const [states,setStates]=useState<Record<number,AutomationState>>(initial);const [busy,setBusy]=useState<Set<number>>(new Set());const [error,setError]=useState("");const [message,setMessage]=useState("");
 const eligible=rows.filter(r=>r.applicationId!==null&&!locked(r)&&(states[r.applicationId!]??r.automationState??"NOT_APPROVED")==="NOT_APPROVED");
 async function toggle(id:number,approve:boolean){setBusy(c=>new Set(c).add(id));setError("");setMessage("");try{const result=await automationAction(id,approve?"approve-prep":"revoke");setStates(c=>({...c,[id]:result.state}));setMessage(`Preparation permission updated: ${automationLabels[result.state]}.`);}catch(caught){setError(caught instanceof Error?caught.message:"Preparation permission could not be updated.");}finally{setBusy(c=>{const next=new Set(c);next.delete(id);return next;});}}
 async function approveVisible(){const ids=eligible.map(r=>r.applicationId!);if(!ids.length)return;setBusy(new Set(ids));setError("");setMessage("");const results=await Promise.allSettled(ids.map(id=>automationAction(id,"approve-prep")));const updates:Record<number,AutomationState>={};const failures:string[]=[];results.forEach((result,index)=>{if(result.status==="fulfilled")updates[ids[index]]=result.value.state;else failures.push(result.reason instanceof Error?result.reason.message:`Application ${ids[index]} could not be approved.`);});setStates(c=>({...c,...updates}));setBusy(new Set());const count=Object.keys(updates).length;if(count)setMessage(`${count} visible application${count===1?"":"s"} approved for preparation.`);if(failures.length)setError(`${failures.length} application${failures.length===1?"":"s"} could not be approved: ${failures.join(" ")}`);}
 if(!rows.length)return <p>No tracked jobs found.</p>;
 return <section aria-labelledby="application-list-heading">
  <div className="application-list__heading"><h2 id="application-list-heading">Applications</h2><button type="button" disabled={!eligible.length||busy.size>0} onClick={()=>void approveVisible()}>{busy.size>1?"Approving visible…":"Approve all eligible visible"}</button></div>
  {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
  <div className="application-table-container"><table className="application-table"><thead><tr><th scope="col">Prepare</th><th scope="col">Company</th><th scope="col">Position</th><th scope="col">Work Arrangement</th><th scope="col">Latest Status</th><th scope="col">Status Date</th><th scope="col">Actions</th></tr></thead>
  <tbody>{rows.map(row=>{const hasApp=row.applicationId!==null;const state=hasApp?states[row.applicationId!]??row.automationState??"NOT_APPROVED":null;const isLocked=locked(row);const saving=hasApp&&busy.has(row.applicationId!);return <tr key={row.jobOpportunityId}>
   <td className="application-table__prepare">{hasApp?<><label title={isLocked?`${lockLabels[row.lockState!]} applications cannot be prepared`:automationLabels[state!]}><input type="checkbox" aria-label={`Approve ${row.positionTitle} for preparation`} checked={state!=="NOT_APPROVED"} disabled={saving||isLocked} onChange={event=>void toggle(row.applicationId!,event.target.checked)}/><span>{saving?"Saving…":automationLabels[state!]}</span></label><span className={`application-lock-badge application-lock-badge--${(row.lockState??"NOT_SUBMITTED").toLowerCase()}`}>{lockLabels[row.lockState??"NOT_SUBMITTED"]}</span></>:<span>Application required</span>}</td>
   <td className="application-table__truncate" title={row.companyName??"Unknown company"}>{row.companyName??"—"}</td><th scope="row" className="application-table__truncate" title={row.positionTitle}>{row.applicationUrl?<a href={row.applicationUrl} target="_blank" rel="noopener noreferrer">{row.positionTitle}</a>:row.positionTitle}</th><td>{remoteLabels[row.remoteType]}</td><td>{row.status?statusLabels[row.status]:"Added"}</td><td>{formatDate(row.statusDate)}</td>
   <td><div className="application-table__actions"><button type="button" aria-label={`Edit ${hasApp?"application":"job"} for ${row.positionTitle}`} onClick={()=>onEdit(row)}>Edit</button>{hasApp&&row.lockState==="NOT_SUBMITTED"&&(row.status==="SAVED"||row.status==="PREPARING")&&<button type="button" className="application-table__compact-action" aria-label={`Mark ${row.positionTitle} as applied`} onClick={()=>onMarkApplied(row)}>Mark Applied</button>}{hasApp?<button type="button" aria-label={`Delete application for ${row.positionTitle}`} disabled={deletingId===row.applicationId} onClick={()=>void onDelete(row)}>{deletingId===row.applicationId?"Deleting…":"Delete"}</button>:<button type="button" aria-label={`Add application for ${row.positionTitle}`} onClick={()=>onAddApplication(row.jobOpportunityId)}>Add application</button>}</div></td>
  </tr>})}</tbody></table></div>
 </section>;
}
