import { render,screen,waitFor,within } from "@testing-library/react";import userEvent from "@testing-library/user-event";import {beforeEach,describe,expect,it,vi} from "vitest";import type {ComponentProps} from "react";
import ApplicationList from "./ApplicationList";import type {ApplicationTrackerRow} from "../types/applicationTracker";import {automationAction,type ApplicationAutomation} from "../api/applicationsApi";
vi.mock("../api/applicationsApi",()=>({automationAction:vi.fn()}));
const row:ApplicationTrackerRow={jobOpportunityId:11,companyId:1,companyName:"A Very Long GitHub Company Name",positionTitle:"Junior Software Engineer",department:"Engineering",location:"New York",remoteType:"HYBRID",employmentType:"Full-time",salaryMin:90000,salaryMax:120000,salaryCurrency:"USD",salaryNotes:null,applicationUrl:"https://example.com/jobs/11",source:"Site",datePosted:"2026-08-01",closingDate:null,priority:1,matchScore:8,jobDescription:null,jobNotes:null,jobCreatedAt:"2026-08-01T10:00:00Z",jobUpdatedAt:"2026-08-02T10:00:00Z",applicationId:101,status:"PHONE_SCREEN",resumeVersion:"SE",coverLetterNeeded:false,portfolioLink:null,githubLink:null,projectsToHighlight:null,skillsToEmphasize:null,interviewTopics:null,recruiterName:null,recruiterEmail:null,applicationDate:"2026-08-07",followUpDate:null,phoneScreenAt:"2026-08-12T14:00:00Z",interviewOneAt:null,interviewTwoAt:null,offerAt:null,rejectedAt:null,applicationNotes:null,applicationCreatedAt:"2026-08-07T10:00:00Z",applicationUpdatedAt:"2026-08-08T10:00:00Z",automationState:"NOT_APPROVED",statusDate:"2026-08-12T14:00:00Z"};
const jobOnly={...row,jobOpportunityId:12,positionTitle:"Operations Engineer",applicationUrl:null,applicationId:null,status:null,automationState:null,statusDate:"2026-08-01T10:00:00Z"} satisfies ApplicationTrackerRow;
const automation=(id:number,state:"NOT_APPROVED"|"APPROVED_FOR_PREP"|"NEEDS_ANSWERS"|"BLOCKED"|"READY_FOR_REVIEW"|"APPROVED_TO_SUBMIT")=>({id,applicationId:id,state,submissionMode:"PREPARE_ONLY" as const,atsType:"UNKNOWN" as const,unresolvedRequiredCount:0,needsReviewCount:0,blockerCount:0,blockReason:null,approvedForPrepAt:null,readyForReviewAt:null,approvedToSubmitAt:null,updatedAt:"2026-08-12T00:00:00Z"});
function renderList(rows:ApplicationTrackerRow[],overrides:Partial<ComponentProps<typeof ApplicationList>>={}){const props={rows,deletingId:null,onEdit:vi.fn(),onDelete:vi.fn().mockResolvedValue(undefined),onAddApplication:vi.fn(),onMarkApplied:vi.fn(),...overrides};render(<ApplicationList {...props}/>);return props;}
describe("ApplicationList",()=>{beforeEach(()=>vi.clearAllMocks());
 it("renders exactly the compact columns and linked position",()=>{renderList([row]);const headers=screen.getAllByRole("columnheader").map(h=>h.textContent);expect(headers).toEqual(["Prepare","Company","Position","Work Arrangement","Latest Status","Status Date","Actions"]);expect(screen.getByText("Phone Screen")).toBeInTheDocument();expect(screen.getByText("Aug 12, 2026")).toBeInTheDocument();const link=screen.getByRole("link",{name:"Junior Software Engineer"});expect(link).toHaveAttribute("href","https://example.com/jobs/11");expect(link).toHaveAttribute("target","_blank");expect(link).toHaveAttribute("rel","noopener noreferrer");expect(screen.queryByText("Full-time")).not.toBeInTheDocument();expect(screen.queryByText("$90,000")).not.toBeInTheDocument();});
 it("renders job-only Added state and Add Application",()=>{renderList([jobOnly]);expect(screen.getByText("Added")).toBeInTheDocument();expect(screen.getByText("Aug 1, 2026")).toBeInTheDocument();expect(screen.getByText("Application required")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Add application for Operations Engineer"})).toBeInTheDocument();});
 it("approves and revokes only after returned backend state",async()=>{const user=userEvent.setup();let resolveApproval!:(value:ApplicationAutomation)=>void;const pending=new Promise<ApplicationAutomation>(resolve=>{resolveApproval=resolve;});vi.mocked(automationAction).mockReturnValueOnce(pending).mockResolvedValueOnce(automation(101,"NOT_APPROVED"));renderList([row]);const checkbox=screen.getByRole("checkbox");await user.click(checkbox);expect(checkbox).toBeDisabled();expect(checkbox).not.toBeChecked();resolveApproval(automation(101,"NEEDS_ANSWERS"));expect(await screen.findByText("Needs answers")).toBeInTheDocument();expect(checkbox).toBeChecked();await user.click(checkbox);await waitFor(()=>expect(checkbox).not.toBeChecked());expect(automationAction).toHaveBeenNthCalledWith(1,101,"approve-prep");expect(automationAction).toHaveBeenNthCalledWith(2,101,"revoke");});
 it("shows blocked and ready derived states without implying readiness",()=>{renderList([{...row,automationState:"BLOCKED"},{...row,jobOpportunityId:13,applicationId:102,positionTitle:"Second Role",automationState:"READY_FOR_REVIEW"}]);expect(screen.getByText("Blocked")).toBeInTheDocument();expect(screen.getByText("Ready for review")).toBeInTheDocument();expect(screen.getAllByRole("checkbox").every(box=>(box as HTMLInputElement).checked)).toBe(true);});
 it("approves every eligible visible application and skips approved/job-only rows",async()=>{const user=userEvent.setup();vi.mocked(automationAction).mockResolvedValue(automation(101,"APPROVED_FOR_PREP"));renderList([row,{...row,jobOpportunityId:13,applicationId:102,automationState:"APPROVED_FOR_PREP"},jobOnly]);await user.click(screen.getByRole("button",{name:"Approve all eligible visible"}));await screen.findByText("1 visible application approved for preparation.");expect(automationAction).toHaveBeenCalledTimes(1);expect(automationAction).toHaveBeenCalledWith(101,"approve-prep");});
 it("reports permission failures and retains row actions",async()=>{const user=userEvent.setup();vi.mocked(automationAction).mockRejectedValue(new Error("Approval blocked"));const props=renderList([row]);await user.click(screen.getByRole("checkbox"));expect(await screen.findByRole("alert")).toHaveTextContent("Approval blocked");expect(screen.getByRole("checkbox")).not.toBeChecked();await user.click(screen.getByRole("button",{name:"Edit application for Junior Software Engineer"}));await user.click(screen.getByRole("button",{name:"Delete application for Junior Software Engineer"}));expect(props.onEdit).toHaveBeenCalledWith(row);expect(props.onDelete).toHaveBeenCalledWith(row);});
 it("uses compact stacked action controls",()=>{renderList([row]);const actions=screen.getByRole("button",{name:/Edit application/}).parentElement!;expect(actions).toHaveClass("application-table__actions");expect(within(actions).getByText("Delete")).toBeInTheDocument();});
 it("offers Mark Applied only for eligible saved or preparing applications",async()=>{const user=userEvent.setup();const saved={...row,status:"SAVED" as const,lockState:"NOT_SUBMITTED" as const};const props=renderList([saved,{...row,jobOpportunityId:13,applicationId:102,status:"SAVED",lockState:"TESTING"}]);await user.click(screen.getByRole("button",{name:"Mark Junior Software Engineer as applied"}));expect(props.onMarkApplied).toHaveBeenCalledWith(saved);expect(screen.getAllByText("Mark Applied")).toHaveLength(1);});
 it("disables preparation and bulk-skips submitted and archived applications",async()=>{const user=userEvent.setup();vi.mocked(automationAction).mockResolvedValue(automation(103,"APPROVED_FOR_PREP"));renderList([{...row,lockState:"SUBMITTED"},{...row,jobOpportunityId:13,applicationId:102,positionTitle:"Archived Role",lockState:"ARCHIVED"},{...row,jobOpportunityId:14,applicationId:103,positionTitle:"Testing Role",lockState:"TESTING"}]);expect(screen.getByText("Submitted")).toBeInTheDocument();expect(screen.getByText("Archived")).toBeInTheDocument();expect(screen.getByText("Testing")).toBeInTheDocument();expect(screen.getByRole("checkbox",{name:/Junior/})).toBeDisabled();expect(screen.getByRole("checkbox",{name:/Archived/})).toBeDisabled();await user.click(screen.getByRole("button",{name:"Approve all eligible visible"}));await screen.findByText("1 visible application approved for preparation.");expect(automationAction).toHaveBeenCalledTimes(1);expect(automationAction).toHaveBeenCalledWith(103,"approve-prep");});
});
