package com.chengukargbo.careeros.automation;
import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.any; import static org.mockito.Mockito.*;
import java.util.Optional; import org.junit.jupiter.api.BeforeEach; import org.junit.jupiter.api.Test; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.test.util.ReflectionTestUtils;
import com.chengukargbo.careeros.applications.*; import com.chengukargbo.careeros.automation.AutomationEnums.*; import com.chengukargbo.careeros.common.exception.BusinessValidationException; import com.chengukargbo.careeros.questions.QuestionReadinessService; import com.chengukargbo.careeros.questions.QuestionReadinessService.Readiness;
@ExtendWith(MockitoExtension.class)
class ApplicationAutomationServiceTest {
 @Mock ApplicationAutomationRepository repository; @Mock ApplicationAutomationHistoryRepository history; @Mock ApplicationRepository applications; @Mock QuestionReadinessService readiness; ApplicationAutomationService service; ApplicationAutomation automation;
 @BeforeEach void setup(){service=new ApplicationAutomationService(repository,history,applications,readiness);automation=new ApplicationAutomation(application());ReflectionTestUtils.setField(automation,"id",3L);lenient().when(repository.findByApplicationId(7L)).thenReturn(Optional.of(automation));lenient().when(repository.save(any())).thenAnswer(i->i.getArgument(0));lenient().when(readiness.assess(7L)).thenReturn(new Readiness(0,0,0,true));}
 @Test void beginsNotApprovedAndRequiresExplicitPreparationApproval(){assertThat(service.get(7L).state()).isEqualTo(State.NOT_APPROVED);assertThat(service.approvePrep(7L).state()).isEqualTo(State.APPROVED_FOR_PREP);verify(history).save(argThat(event->event.getSource()==Source.USER&&event.getPreviousState()==State.NOT_APPROVED));}
 @Test void invalidJumpAndDirectSubmissionAreRejected(){assertThatThrownBy(()->service.markReady(7L)).isInstanceOf(BusinessValidationException.class);assertThatThrownBy(()->service.approveSubmit(7L)).isInstanceOf(BusinessValidationException.class);}
 @Test void requiredQuestionsAndBlockersPreventReadiness(){service.approvePrep(7L);when(readiness.assess(7L)).thenReturn(new Readiness(1,1,0,false));assertThatThrownBy(()->service.markReady(7L)).hasMessageContaining("Required questions");when(readiness.assess(7L)).thenReturn(new Readiness(0,0,1,false));service.recalculate(7L);assertThat(automation.getState()).isEqualTo(State.BLOCKED);}
 @Test void userCheckpointsReachApprovedToSubmitOnlyWhenReady(){service.approvePrep(7L);assertThat(service.markReady(7L).state()).isEqualTo(State.READY_FOR_REVIEW);assertThat(service.approveSubmit(7L).state()).isEqualTo(State.APPROVED_TO_SUBMIT);verify(history,times(3)).save(any());}
 @Test void unsafeQuestionChangeDemotesApprovedSubmission(){service.approvePrep(7L);service.markReady(7L);service.approveSubmit(7L);when(readiness.assess(7L)).thenReturn(new Readiness(1,0,0,false));service.recalculate(7L);assertThat(automation.getState()).isEqualTo(State.NEEDS_ANSWERS);verify(history).save(argThat(event->event.getSource()==Source.SYSTEM&&event.getPreviousState()==State.APPROVED_TO_SUBMIT));}
 @Test void revocationPreservesApplicationAndPreparationData(){service.approvePrep(7L);assertThat(service.revoke(7L).state()).isEqualTo(State.NOT_APPROVED);verifyNoInteractions(applications);}
 @Test void atsMetadataIsAllowListedAndHasNoBehavior(){assertThat(service.setAts(7L,AtsType.GREENHOUSE).atsType()).isEqualTo(AtsType.GREENHOUSE);assertThat(automation.getState()).isEqualTo(State.NOT_APPROVED);}
 @Test void generatedReviewPackageMeansManualReviewEvenWithBlockers(){service.approvePrep(7L);when(readiness.assess(7L)).thenReturn(new Readiness(1,0,1,false));assertThat(service.reviewPackageReady(7L).state()).isEqualTo(State.READY_FOR_REVIEW);service.recalculate(7L);assertThat(automation.getState()).isEqualTo(State.READY_FOR_REVIEW);verify(history).save(argThat(event->event.getSource()==Source.AUTOMATION&&event.getNewState()==State.READY_FOR_REVIEW));}
 private Application application(){Application app=new Application(null,ApplicationStatus.SAVED,null,false,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);ReflectionTestUtils.setField(app,"id",7L);return app;}
}
