package com.chengukargbo.careeros.automation;
import java.util.List; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.chengukargbo.careeros.applications.*; import com.chengukargbo.careeros.automation.AutomationDtos.*; import com.chengukargbo.careeros.automation.AutomationEnums.*; import com.chengukargbo.careeros.common.exception.BusinessValidationException; import com.chengukargbo.careeros.questions.QuestionReadinessService; import com.chengukargbo.careeros.applications.lock.ApplicationLockGuard;
@Service @Transactional
public class ApplicationAutomationService {private final ApplicationAutomationRepository repository;private final ApplicationAutomationHistoryRepository history;private final ApplicationRepository applications;private final QuestionReadinessService readiness;private final ApplicationLockGuard lockGuard;
 public ApplicationAutomationService(ApplicationAutomationRepository r,ApplicationAutomationHistoryRepository h,ApplicationRepository a,QuestionReadinessService q,ApplicationLockGuard lockGuard){repository=r;history=h;applications=a;readiness=q;this.lockGuard=lockGuard;}
 public void initialize(Application application){if(repository.findByApplicationId(application.getId()).isEmpty())repository.save(new ApplicationAutomation(application));}
 @Transactional public Response get(Long applicationId){return response(find(applicationId));}
 public Response approvePrep(Long id){lockGuard.requireLiveInteraction(id);ApplicationAutomation a=find(id);require(a,State.NOT_APPROVED);move(a,State.APPROVED_FOR_PREP,Source.USER,"User approved application preparation");recalculate(id);return response(a);}
 public Response markReady(Long id){ApplicationAutomation a=find(id);if(a.getState()!=State.APPROVED_FOR_PREP&&a.getState()!=State.NEEDS_ANSWERS)throw invalid(a,State.READY_FOR_REVIEW);if(!readiness.assess(id).ready())throw new BusinessValidationException("Required questions must be approved and blockers resolved before review");move(a,State.READY_FOR_REVIEW,Source.USER,"User marked preparation ready for review");return response(a);}
 public Response reviewPackageReady(Long id){ApplicationAutomation a=find(id);if(a.getState()==State.NOT_APPROVED)throw new BusinessValidationException("Application is not approved for preparation");if(a.getState()!=State.READY_FOR_REVIEW)move(a,State.READY_FOR_REVIEW,Source.AUTOMATION,"Preparation review package generated for manual review");return response(a);}
 public Response approveSubmit(Long id){ApplicationAutomation a=find(id);require(a,State.READY_FOR_REVIEW);if(!readiness.assess(id).ready())throw new BusinessValidationException("Application is not ready for submission approval");move(a,State.APPROVED_TO_SUBMIT,Source.USER,"User approved future submission");return response(a);}
 public Response revoke(Long id){ApplicationAutomation a=find(id);if(a.getState()!=State.NOT_APPROVED)move(a,State.NOT_APPROVED,Source.USER,"User revoked preparation permission");return response(a);}
 public Response setAts(Long id,AtsType ats){ApplicationAutomation a=find(id);a.setAtsType(ats==null?AtsType.UNKNOWN:ats);return response(repository.save(a));}
 public void recalculate(Long id){ApplicationAutomation a=repository.findByApplicationId(id).orElse(null);if(a==null||a.getState()==State.NOT_APPROVED||a.getState()==State.READY_FOR_REVIEW)return;var r=readiness.assess(id);State next=null;String reason=null;if(r.blockers()>0){next=State.BLOCKED;reason="Question blocker prevents preparation";}else if(!r.ready()){next=State.NEEDS_ANSWERS;reason="Required questions need answers or review";}else if(a.getState()==State.NEEDS_ANSWERS||a.getState()==State.BLOCKED){next=State.APPROVED_FOR_PREP;reason="Question blockers resolved; user review checkpoint restored";}if(next!=null&&next!=a.getState())move(a,next,Source.SYSTEM,reason);}
 @Transactional(readOnly=true) public List<HistoryResponse> history(Long id){applications.findById(id).orElseThrow(()->new ApplicationNotFoundException(id));return history.findByApplicationIdOrderByOccurredAtAscIdAsc(id).stream().map(HistoryResponse::from).toList();}
 @Transactional(readOnly=true) public State findExistingState(Long id){return repository.findByApplicationId(id).map(ApplicationAutomation::getState).orElse(State.NOT_APPROVED);}
 private ApplicationAutomation find(Long id){return repository.findByApplicationId(id).orElseGet(()->{Application app=applications.findById(id).orElseThrow(()->new ApplicationNotFoundException(id));ApplicationAutomation created=new ApplicationAutomation(app);return repository.save(created);});}
 private void require(ApplicationAutomation a,State expected){if(a.getState()!=expected)throw invalid(a,expected);}
 private BusinessValidationException invalid(ApplicationAutomation a,State target){return new BusinessValidationException("Cannot transition automation from "+a.getState()+" to "+target);}
 private void move(ApplicationAutomation a,State next,Source source,String reason){State previous=a.getState();a.transition(next);if(next==State.BLOCKED)a.setBlockReason(reason);repository.save(a);history.save(new ApplicationAutomationHistory(a,previous,next,source,reason));}
 private Response response(ApplicationAutomation a){return Response.from(a,readiness.assess(a.getApplication().getId()));}
}
