spring.application.name=CareerOS

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/career_os
spring.datasource.username=career_os
spring.datasource.password=career_os_dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration