package com.chengukargbo.careeros.applications.lock;

import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.any;import static org.mockito.Mockito.*;
import java.util.*;import org.junit.jupiter.api.*;import org.springframework.test.util.ReflectionTestUtils;
import com.chengukargbo.careeros.applications.*;import com.chengukargbo.careeros.common.exception.BusinessValidationException;import com.chengukargbo.careeros.preparation.ApplicationPreparationService;

class ApplicationLockServiceTest {
 private ApplicationLockRepository locks=mock(ApplicationLockRepository.class);private ApplicationLockHistoryRepository history=mock(ApplicationLockHistoryRepository.class);private ApplicationRepository applications=mock(ApplicationRepository.class);private ApplicationPreparationService preparation=mock(ApplicationPreparationService.class);private ApplicationLockService service;private Application application;private ApplicationLock lock;
 @BeforeEach void setUp(){application=mock(Application.class);when(application.getId()).thenReturn(9L);when(application.getStatus()).thenReturn(ApplicationStatus.SAVED);when(applications.findById(9L)).thenReturn(Optional.of(application));lock=new ApplicationLock(application,ApplicationLockState.NOT_SUBMITTED,"Initial");ReflectionTestUtils.setField(lock,"id",1L);when(locks.findByApplicationId(9L)).thenReturn(Optional.of(lock));when(locks.save(any())).thenAnswer(i->i.getArgument(0));service=new ApplicationLockService(locks,history,applications,preparation);}
 @Test void supportsTestingArchiveAndRestoreWithAppendOnlyHistory(){assertThat(service.markTesting(9L,null).lockState()).isEqualTo(ApplicationLockState.TESTING);assertThat(service.restore(9L,null).lockState()).isEqualTo(ApplicationLockState.NOT_SUBMITTED);assertThat(service.archive(9L,"Done").lockState()).isEqualTo(ApplicationLockState.ARCHIVED);assertThat(service.restore(9L,null).lockState()).isEqualTo(ApplicationLockState.NOT_SUBMITTED);verify(history,times(4)).save(any());verify(preparation).cancelActiveForLock(9L,"ARCHIVED");}
 @Test void rejectsSubmittedWithoutLifecycleEvidence(){assertThatThrownBy(()->service.markSubmitted(9L,null)).isInstanceOf(BusinessValidationException.class).hasMessageContaining("lifecycle");verifyNoInteractions(history,preparation);}
 @Test void submittedEvidenceAllowsLockAndCancelsActiveSession(){when(application.getStatus()).thenReturn(ApplicationStatus.APPLIED);assertThat(service.markSubmitted(9L,null).lockState()).isEqualTo(ApplicationLockState.SUBMITTED);verify(preparation).cancelActiveForLock(9L,"SUBMITTED");verify(history).save(argThat(event->event.getPreviousLock()==ApplicationLockState.NOT_SUBMITTED&&event.getNewLock()==ApplicationLockState.SUBMITTED&&event.getSource()==ApplicationLockSource.USER));}
 @Test void deterministicInitializationNeverCreatesTestingOrUserHistory(){when(locks.findByApplicationId(9L)).thenReturn(Optional.empty(),Optional.of(lock));when(application.getStatus()).thenReturn(ApplicationStatus.PHONE_SCREEN);service.initialize(application);verify(locks).save(argThat(created->created.getState()==ApplicationLockState.SUBMITTED));verify(history).save(argThat(event->event.getSource()==ApplicationLockSource.SYSTEM&&event.getNewLock()==ApplicationLockState.SUBMITTED));}
}
